#5 First steps towards Java 11 scanning!
Unfortunately the following error is produced when the plugin is executed:
Execution default-cli of goal org.hjug.refactorfirst.plugin:refactor-first-maven-plugin:0.1.2-SNAPSHOT:report failed: An API incompatibility was encountered while executing org.hjug.refactorfirst.plugin:refactor-first-maven-plugin:0.1.2-SNAPSHOT:report: java.lang.NoSuchMethodError: 'int org.apache.commons.lang3.mutable.MutableInt.incrementAndGet()'

It appears that Maven loads an older version of commons-lang 3 first that doesn't have the version that PMD uses, and as a result the method isn't found.  Will need to try with an older version of PMD that uses the same version of commons-lang 3 as Maven.